# Practice Lab: SQLite in Python

You work at a sports data consulting firm that provides insights to basketball teams, broadcasters, and sports media outlets. You are tasked with finding out which teams are most consistent and which players are the most impactful. 

To complete the task you decide to analyze the NBA Boxscore Dataset, which includes 3 tables:

- **game_info**: contains information about each game between two teams, including things like the scores and the outcome.
- **team_stats**: contains detailed statistics for each team in each game, such as points scored, rebounds, assists, and more.
- **player_stats**: contains individual game stats for each player, including points, assists, rebounds, and other performance details.

## Data Schema
The next diagram shows the data schema. For simplicity, it only shows a subset of columns for each table.

<div style="text-align: center">
    <img src="imgs/NBA-db-relation.png" width=400>
</div>

## General instructions
- **Replace any instances of `None` with your own code**. All `None`s must be replaced.
- **Compare your results with the expected output** shown below the code.
- **Check the solution** using the expandable cell to verify your answer. If needed, you can copy the code and paste it into the cell

Happy coding!

<div style="background-color: #FAD888; padding: 10px; border-radius: 3px; box-shadow: 0 2px 4px rgba(0, 0, 0, 0.1); width:95%
">
<strong>Important note</strong>: Code blocks with None will not run properly. If you run them before completing the exercise, you will likely get an error. 
</div>

## Table of contents
- [Step 1: Import modules](#import-modules)
- [Step 2: Connect to the Database](#connect-to-the-database)
    - [Checking the Connection](#checking-the-connection)
- [Step 3: Best players](#step3)

<a id="import-modules"></a>

## Import modules
Begin by importing sqlite3 and pandas modules.

In [1]:
import sqlite3
import pandas as pd

<a id="connect-to-the-database"></a>

## Connect to the Database
Next, you need to establish a connection to the SQLite database to run queries and retrieve the data.

<div style="background-color: #C6E2FF; padding: 10px; border-radius: 3px; box-shadow: 0 2px 4px rgba(0, 0, 0, 0.1); width:95%
">

**▶▶▶ Directions**
1. Create a connection to the "basketball.db" database

</div>

In [2]:
### START CODE HERE ###

# Connect to the SQLite database
connection = sqlite3.connect("basketball.db")

### END CODE HERE ###

<details>
<summary style="background-color: #FDBFC7; padding: 10px; border-radius: 3px; box-shadow: 0 2px 4px rgba(0, 0, 0, 0.1); width: 95%; text-align: left; cursor: pointer; font-weight: bold;">
Click here to see the solution</summary> 

<ul style="background-color: #FFF8F8; padding: 10px; border-radius: 3px; margin-top: 5px; width: 95%; box-shadow: inset 0 2px 4px rgba(0, 0, 0, 0.1);">
   
Your solution should look something like this:

```python
# Connect to the SQLite database
connection = sqlite3.connect("basketball.db")

```
</details>

<a id="checking-the-connection"></a>

### Checking the connection

In order to check the connection, you can retrieve the first rows of one of the tables.

<div style="background-color: #C6E2FF; padding: 10px; border-radius: 3px; box-shadow: 0 2px 4px rgba(0, 0, 0, 0.1); width:95%
">

**▶▶▶ Directions**
1. Write a SQLite query to select the first row of the `game_info` table
2. Execute the query using the `pd.read_sql_query()` function
4. Print the results

</div>

In [3]:
### START CODE HERE ###

# write the SQL query
first_row_query = """
SELECT * 
FROM game_info 
LIMIT 1;
"""

# run the query 
first_row_df = pd.read_sql_query(first_row_query, connection)

### END CODE HERE ###

# show the results
first_row_df

,game_id,season,date,away_team,away_score,home_team,home_score,result
0,131410290001,1314,2013-10-29,ORL,87,IND,97,1

<details open>
<summary style="background-color: #c6e2ff6c; padding: 10px; border-radius: 3px; box-shadow: 0 2px 4px rgba(0, 0, 0, 0.01); width: 95%; text-align: left; cursor: pointer; font-weight: bold;">
Expected output:</summary> 

<br>
<img src="imgs/first_row.png" width="600px">

</details>

<details>
<summary style="background-color: #FDBFC7; padding: 10px; border-radius: 3px; box-shadow: 0 2px 4px rgba(0, 0, 0, 0.1); width: 95%; text-align: left; cursor: pointer; font-weight: bold;">
Click here to see the solution</summary> 

<ul style="background-color: #FFF8F8; padding: 10px; border-radius: 3px; margin-top: 5px; width: 95%; box-shadow: inset 0 2px 4px rgba(0, 0, 0, 0.1);">
   
Your solution should look something like this:

```python
# Write the SQL query
first_row_query = """
SELECT * 
FROM game_info 
LIMIT 1;
"""

# run the query 
first_row_df = pd.read_sql_query(first_row_query, connection)

```
</details>

<a id="step3"></a>

## Step 3: Best players

You want to know which are the 10 players with the most points scored (`PTS`), and which team they play for.

<div style="background-color: #C6E2FF; padding: 10px; border-radius: 3px; box-shadow: 0 2px 4px rgba(0, 0, 0, 0.1); width: 95%;">

▶▶▶ **Directions** 
1. Write a query that:
    - Selects the columns `player`, `team`, and `PTS` from the `player_stats` table.
    - Sorts the results by `PTS` in descending order.
    - Limits the results to the top 10 players.
2. Execute the query using the `pd.read_sql_query()` function
4. Print the results
</div>

In [5]:
### START CODE HERE ###

# write the SQL query
best_players_query = """
SELECT player, team, PTS
FROM player_stats 
ORDER BY PTS DESC
LIMIT 10;
"""

# run the query
best_players_df = pd.read_sql_query(best_players_query, connection)

### END CODE HERE ###

# show the results
best_players_df

             player team   PTS
0  Donovan Mitchell  CLE  71.0
1    Damian Lillard  POR  71.0
2      Devin Booker  PHO  70.0
3   Carmelo Anthony  NYK  62.0
4     Stephen Curry  GSW  62.0
5      LeBron James  MIA  61.0
6      James Harden  HOU  61.0
7      James Harden  HOU  61.0
8    Damian Lillard  POR  61.0
9    Damian Lillard  POR  61.0

<details open>
<summary style="background-color: #c6e2ff6c; padding: 10px; border-radius: 3px; box-shadow: 0 2px 4px rgba(0, 0, 0, 0.01); width: 95%; text-align: left; cursor: pointer; font-weight: bold;">
Expected output:</summary> 


<br>
<img src="imgs/q3df.png" width="200">

</details>

<details>
<summary style="background-color: #FDBFC7; padding: 10px; border-radius: 3px; box-shadow: 0 2px 4px rgba(0, 0, 0, 0.1); width: 95%; text-align: left; cursor: pointer; font-weight: bold;">
Click here to see the solution</summary> 

<ul style="background-color: #FFF8F8; padding: 10px; border-radius: 3px; margin-top: 5px; width: 95%; box-shadow: inset 0 2px 4px rgba(0, 0, 0, 0.1);">
   
Your solution should look something like this:

<small>

```python
# write the SQL query
best_players_query = """
SELECT player, team, PTS
FROM player_stats 
ORDER BY PTS DESC
LIMIT 10;
"""

# run the query
best_players_df = pd.read_sql_query(best_players_query, connection)

```
</small>
</details>

Once you are done, don't forget to close the connection!

In [6]:
connection.close()

Congratulations for making it until the end of this lab. You will keep working on this dataset in Lesson 2. Hope you enjoyed it!