# C3M4 Lesson 3 Practice Lab: London housing prices - Regression with categorical data

In the previous lab, you managed to create a simple linear regression to predict a house value based on the floor area. While this is a major factor, other variables like the location and number of bathrooms also influence prices. By including these features in a multiple linear regression model, you can capture the combined effects of both numerical and categorical variables to produce a more accurate price prediction.

In this lab you will be working with the following columns:

- `floorAreaSqM`: The area in square meters of the property.
- `bathrooms`: Number of bathrooms
- `region`: The part of London
- `price`: The price of the sale 

## General instructions
- **Replace any instances of `None` with your own code**. All `None`s must be replaced.
- **Compare your results with the expected output** shown below the code.
- **Check the solution** using the expandable cell to verify your answer.

Happy coding!

<div style="background-color: #FAD888; padding: 10px; border-radius: 3px; box-shadow: 0 2px 4px rgba(0, 0, 0, 0.1); width:95%
">
<strong>Important note</strong>: Code blocks with None will not run properly. If you run them before completing the exercise, you will likely get an error. 
</div>

## Table of contents
- [Step 1: Import libraries](#import-libraries)
- [Step 2: Load the data](#load-the-data)
- [Step 3: Including categorical data](#cat-data)
- [Step 4: Train your model](#train-your-model)
    - [Improving the model](#improving-the-model)

<a id="import-libraries"></a>

## Step 1: Import libraries
Begin by importing the needed libraries.

In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import statsmodels.api as sm

<a id="load-the-data"></a>

## Step 2: Load the data
Next, you will be loading the data. Run the cell below to load the data.

In [2]:
df = pd.read_csv("london_house_price_2018.csv")
df.head()

,fullAddress,postcode,outcode,latitude,longitude,bathrooms,bedrooms,floorAreaSqM,livingRooms,tenure,propertyType,currentEnergyRating,price,region
0,"Flat 1, White Rose Court, Widegate Street, Lon...",E1 7ES,E1,51.517972,-0.078028,2.0,2.0,73.0,1.0,Leasehold,Purpose Built Flat,D,623000,E Inner
1,"Flat 5, White Rose Court, Widegate Street, Lon...",E1 7ES,E1,51.517972,-0.078028,1.0,2.0,50.0,1.0,Leasehold,Converted Flat,E,575000,E Inner
2,"9A Petticoat Tower, Petticoat Square, London, ...",E1 7EE,E1,51.515798,-0.077081,1.0,2.0,72.0,2.0,Leasehold,Purpose Built Flat,C,385000,E Inner
3,"Flat 11, Arcadia Court, 45 Old Castle Street, ...",E1 7NY,E1,51.516568,-0.074793,1.0,1.0,42.0,1.0,Leasehold,Purpose Built Flat,D,370000,E Inner
4,"Flat 18, Arcadia Court, 45 Old Castle Street, ...",E1 7NY,E1,51.516568,-0.074793,1.0,1.0,39.0,1.0,Leasehold,Purpose Built Flat,C,364000,E Inner

<a id="cat-data"></a>

## Step 3: Including categorical data
You already know that the borough, where the property is located influences the price. You confirmed this in the first lab of this module with a hypothesis test. You should definitely include this information in your model. Since `outcode` has too many options, you will use the `region` column instead, which includes data about the borough and whether the property is considered to be outer or inner city.

<div style="background-color: #C6E2FF; padding: 10px; border-radius: 3px; box-shadow: 0 2px 4px rgba(0, 0, 0, 0.1); width:95%
">

**▶▶▶ Directions**
1. Use the `"floorAreaSqM"` and `"region"` as predictors.
2. Crete a dataframe `features_with_dummies`, which includes all the predictors and gas the relevant columns turned into dummy variables.
    - Use `pd.get_dummies()` to achieve that.
    - Dont forget to drop the first of the dummies and set the data type to `int`.

</div>

In [3]:
### START CODE HERE ###

# use "floorAreaSqM" and "region" as predictors
predictors = ["floorAreaSqM", "region"]

# get the dummy variables for the region column
features_with_dummies = pd.get_dummies(df[predictors],
                                drop_first=True,
                                dtype=int)

### END CODE HERE ###


# explore the DataFrame
features_with_dummies.head()

,floorAreaSqM,region_E Outer,region_EC Inner,region_IG Outer,region_N Inner,region_N Outer,region_NW Inner,region_NW Outer,region_Other,region_SE Inner,region_SE Outer,region_SW Inner,region_SW Outer,region_W Inner,region_W Outer,region_WC Inner
0,73.0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
1,50.0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
2,72.0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
3,42.0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
4,39.0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0

<details open>
<summary style="background-color: #c6e2ff6c; padding: 10px; border-radius: 3px; box-shadow: 0 2px 4px rgba(0, 0, 0, 0.01); width: 95%; text-align: left; cursor: pointer; font-weight: bold;">
Expected output:</summary> 

<img src="imgsL3/dfwith_dummies.png" width="1000">
</details>

<details>
<summary style="background-color: #FDBFC7; padding: 10px; border-radius: 3px; box-shadow: 0 2px 4px rgba(0, 0, 0, 0.1); width: 95%; text-align: left; cursor: pointer; font-weight: bold;">
Click here to see the solution</summary> 

<ul style="background-color: #FFF8F8; padding: 10px; border-radius: 3px; margin-top: 5px; width: 95%; box-shadow: inset 0 2px 4px rgba(0, 0, 0, 0.1);">
   
Your solution should look something like this:

```python
# use "floorAreaSqM" and "region" as predictors
predictors = ["floorAreaSqM", "region"]

# get the dummy variables for the region column
features_with_dummies = pd.get_dummies(df[predictors],
                                drop_first=True,
                                dtype=int)
```
</details>

Now that your features are ready, create and train your multiple linear regression model!
<a id="train-your-model"></a>

## Step 4: Train your model

<div style="background-color: #C6E2FF; padding: 10px; border-radius: 3px; box-shadow: 0 2px 4px rgba(0, 0, 0, 0.1); width:95%
">

**▶▶▶ Directions**
1. Save the dependent variable (`"price"`) into a variable named `Y`.
2. Add the constant term of the model to your DataFrame of features (`features_with_dummies`) and save it into a new variable called `X`.
4. Define and train the model using the `sm.OLS()` function, and the `fit()` method respectively.
5. Print the model summary.
</div>

In [5]:
### START CODE HERE ###

# get the dependent variable
Y = df["price"]

# add the constant term to the independent variables
X = sm.add_constant(features_with_dummies)

# create the model
model = sm.OLS(Y, X)

# fit the model
results = model.fit()

# print the summary
print(results.summary())

### END CODE HERE ###

                            OLS Regression Results
==============================================================================
Dep. Variable:                  price   R-squared:                       0.509
Model:                            OLS   Adj. R-squared:                  0.509
Method:                 Least Squares   F-statistic:                     5235.
Date:                Mon, 08 Jun 2026   Prob (F-statistic):               0.00
Time:                        08:09:53   Log-Likelihood:            -1.1968e+06
No. Observations:               80703   AIC:                         2.394e+06
Df Residuals:                   80686   BIC:                         2.394e+06
Df Model:                          16
Covariance Type:            nonrobust
===================================================================================
                      coef    std err          t      P>|t|      [0.025      0.975]
-----------------------------------------------------------------------------------
const           -2.712e+05   1.07e+04    -25.352      0.000   -2.92e+05    -2.5e+05
floorAreaSqM     1.058e+04     42.175    250.876      0.000    1.05e+04    1.07e+04
region_E Outer  -2.071e+05   1.26e+04    -16.469      0.000   -2.32e+05   -1.82e+05
region_EC Inner  3.697e+05   2.24e+04     16.473      0.000    3.26e+05    4.14e+05
region_IG Outer -4.821e+04   6.67e+05     -0.072      0.942   -1.36e+06    1.26e+06
region_N Inner  -3.272e+04   1.32e+04     -2.485      0.013   -5.85e+04   -6912.733
region_N Outer  -2.326e+05   1.25e+04    -18.577      0.000   -2.57e+05   -2.08e+05
region_NW Inner  3.554e+05   1.69e+04     20.966      0.000    3.22e+05    3.89e+05
region_NW Outer -2.019e+05   1.54e+04    -13.126      0.000   -2.32e+05   -1.72e+05
region_Other     1.064e+06   1.64e+04     64.704      0.000    1.03e+06     1.1e+06
region_SE Inner -6.605e+04   1.24e+04     -5.328      0.000   -9.03e+04   -4.17e+04
region_SE Outer -2.446e+05   1.15e+04    -21.237      0.000   -2.67e+05   -2.22e+05
region_SW Inner  2.172e+05   1.28e+04     17.015      0.000    1.92e+05    2.42e+05
region_SW Outer -7.208e+04   1.31e+04     -5.517      0.000   -9.77e+04   -4.65e+04
region_W Inner   4.904e+05   1.52e+04     32.286      0.000    4.61e+05     5.2e+05
region_W Outer  -7.914e+04   1.54e+04     -5.149      0.000   -1.09e+05    -4.9e+04
region_WC Inner  4.974e+05   2.63e+04     18.938      0.000    4.46e+05    5.49e+05
==============================================================================
Omnibus:                   162754.470   Durbin-Watson:                   1.415
Prob(Omnibus):                  0.000   Jarque-Bera (JB):       1146911446.865
Skew:                          16.339   Prob(JB):                         0.00
Kurtosis:                     586.102   Cond. No.                     3.37e+04
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 3.37e+04. This might indicate that there are
strong multicollinearity or other numerical problems.

<details open>
<summary style="background-color: #c6e2ff6c; padding: 10px; border-radius: 3px; box-shadow: 0 2px 4px rgba(0, 0, 0, 0.01); width: 95%; text-align: left; cursor: pointer; font-weight: bold;">
Expected output:</summary> 

<br>
<span style="font-size: 11px;">

```mkdn
                            OLS Regression Results                            
==============================================================================
Dep. Variable:                  price   R-squared:                       0.509
Model:                            OLS   Adj. R-squared:                  0.509
Method:                 Least Squares   F-statistic:                     5235.
Date:                Tue, 01 Apr 2025   Prob (F-statistic):               0.00
Time:                        15:18:37   Log-Likelihood:            -1.1968e+06
No. Observations:               80703   AIC:                         2.394e+06
Df Residuals:                   80686   BIC:                         2.394e+06
Df Model:                          16                                         
Covariance Type:            nonrobust                                         
===================================================================================
                      coef    std err          t      P>|t|      [0.025      0.975]
-----------------------------------------------------------------------------------
const           -2.712e+05   1.07e+04    -25.352      0.000   -2.92e+05    -2.5e+05
floorAreaSqM     1.058e+04     42.175    250.876      0.000    1.05e+04    1.07e+04
region_E Outer  -2.071e+05   1.26e+04    -16.469      0.000   -2.32e+05   -1.82e+05
region_EC Inner  3.697e+05   2.24e+04     16.473      0.000    3.26e+05    4.14e+05
region_IG Outer -4.821e+04   6.67e+05     -0.072      0.942   -1.36e+06    1.26e+06
region_N Inner  -3.272e+04   1.32e+04     -2.485      0.013   -5.85e+04   -6912.733
region_N Outer  -2.326e+05   1.25e+04    -18.577      0.000   -2.57e+05   -2.08e+05
region_NW Inner  3.554e+05   1.69e+04     20.966      0.000    3.22e+05    3.89e+05
region_NW Outer -2.019e+05   1.54e+04    -13.126      0.000   -2.32e+05   -1.72e+05
region_Other     1.064e+06   1.64e+04     64.704      0.000    1.03e+06     1.1e+06
region_SE Inner -6.605e+04   1.24e+04     -5.328      0.000   -9.03e+04   -4.17e+04
region_SE Outer -2.446e+05   1.15e+04    -21.237      0.000   -2.67e+05   -2.22e+05
region_SW Inner  2.172e+05   1.28e+04     17.015      0.000    1.92e+05    2.42e+05
region_SW Outer -7.208e+04   1.31e+04     -5.517      0.000   -9.77e+04   -4.65e+04
region_W Inner   4.904e+05   1.52e+04     32.286      0.000    4.61e+05     5.2e+05
region_W Outer  -7.914e+04   1.54e+04     -5.149      0.000   -1.09e+05    -4.9e+04
region_WC Inner  4.974e+05   2.63e+04     18.938      0.000    4.46e+05    5.49e+05
==============================================================================
Omnibus:                   162754.470   Durbin-Watson:                   1.415
Prob(Omnibus):                  0.000   Jarque-Bera (JB):       1146911446.865
Skew:                          16.339   Prob(JB):                         0.00
Kurtosis:                     586.102   Cond. No.                     3.37e+04
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 3.37e+04. This might indicate that there are
strong multicollinearity or other numerical problems.
```
</span>
</details>

<details>
<summary style="background-color: #FDBFC7; padding: 10px; border-radius: 3px; box-shadow: 0 2px 4px rgba(0, 0, 0, 0.1); width: 95%; text-align: left; cursor: pointer; font-weight: bold;">
Click here to see the solution</summary> 

<ul style="background-color: #FFF8F8; padding: 10px; border-radius: 3px; margin-top: 5px; width: 95%; box-shadow: inset 0 2px 4px rgba(0, 0, 0, 0.1);">
   
Your solution should look something like this:

```python
# get the dependent variable
Y = df["price"]

# add the constant term to the independent variables
X = sm.add_constant(features_with_dummies)

# create the model
model = sm.OLS(Y, X)

# fit the model
results = model.fit()

# print the summary
print(results.summary())

```
</details>

Adding the dummy variables improved the R-squared of the base model, going from 0.418 to 0.509, which is almost a 25% increase!

Do you think you could improve the model by adding some other features?

<a id="improving-the-model"></a>

### Improving the Model

In the previous lab, you have looked at the correlations of all variables and determined that `"floorAreaSqM"` correlatest the strongest with `"price"`. The second strongest is the `"bathrooms"` variable. Create a new model below, where you use both of these variables in addition to the dummy variables from the `"region"` categorical variable.

<div style="background-color: #C6E2FF; padding: 10px; border-radius: 3px; box-shadow: 0 2px 4px rgba(0, 0, 0, 0.1); width:95%;">

**▶▶▶ Directions**
1. Use `"floorAreaSqM"`, `"bathrooms"` and `"region"` as predictors.
2. Create a dataframe of features with dummy variables using `pd.get_dummies()`
3. Add the constant term and save the result in the variable `X`.
4. Save the dependent variable (`"price"`) into a variable named `Y`.
5. Define and train the model using the `sm.OLS()` function and the `fit()` method respectively.
6. Print the model summary.
</div>

In [6]:
### START CODE HERE ###

# use "floorAreaSqM", "bathrooms" and "region" as predictors
predictors = ["floorAreaSqM", "bathrooms", "region"]

# get the dummy variables for the region column
features_with_dummies = pd.get_dummies(df[predictors], drop_first=True, dtype=int)

# add the constant term
X = sm.add_constant(features_with_dummies)

# get the target variable
Y = df["price"]

# create the model
model = sm.OLS(Y, X)

# fit the model
results = model.fit()

# print the model summary
print(results.summary())

### END CODE HERE ###

                            OLS Regression Results
==============================================================================
Dep. Variable:                  price   R-squared:                       0.520
Model:                            OLS   Adj. R-squared:                  0.520
Method:                 Least Squares   F-statistic:                     5142.
Date:                Mon, 08 Jun 2026   Prob (F-statistic):               0.00
Time:                        08:12:42   Log-Likelihood:            -1.1959e+06
No. Observations:               80703   AIC:                         2.392e+06
Df Residuals:                   80685   BIC:                         2.392e+06
Df Model:                          17
Covariance Type:            nonrobust
===================================================================================
                      coef    std err          t      P>|t|      [0.025      0.975]
-----------------------------------------------------------------------------------
const           -3.902e+05   1.09e+04    -35.644      0.000   -4.12e+05   -3.69e+05
floorAreaSqM     9031.0844     55.507    162.702      0.000    8922.292    9139.877
bathrooms        1.859e+05   4392.856     42.321      0.000    1.77e+05    1.95e+05
region_E Outer  -1.876e+05   1.24e+04    -15.071      0.000   -2.12e+05   -1.63e+05
region_EC Inner  3.388e+05   2.22e+04     15.256      0.000    2.95e+05    3.82e+05
region_IG Outer  1.663e+04    6.6e+05      0.025      0.980   -1.28e+06    1.31e+06
region_N Inner  -1.871e+04    1.3e+04     -1.436      0.151   -4.42e+04    6821.538
region_N Outer   -2.05e+05   1.24e+04    -16.529      0.000   -2.29e+05   -1.81e+05
region_NW Inner   3.37e+05   1.68e+04     20.098      0.000    3.04e+05     3.7e+05
region_NW Outer -2.045e+05   1.52e+04    -13.444      0.000   -2.34e+05   -1.75e+05
region_Other     1.006e+06   1.63e+04     61.656      0.000    9.74e+05    1.04e+06
region_SE Inner -5.472e+04   1.23e+04     -4.462      0.000   -7.88e+04   -3.07e+04
region_SE Outer -2.057e+05   1.14e+04    -18.000      0.000   -2.28e+05   -1.83e+05
region_SW Inner  2.056e+05   1.26e+04     16.287      0.000    1.81e+05     2.3e+05
region_SW Outer -6.412e+04   1.29e+04     -4.961      0.000   -8.94e+04   -3.88e+04
region_W Inner   4.653e+05    1.5e+04     30.948      0.000    4.36e+05    4.95e+05
region_W Outer  -7.819e+04   1.52e+04     -5.143      0.000   -1.08e+05   -4.84e+04
region_WC Inner  4.786e+05    2.6e+04     18.418      0.000    4.28e+05     5.3e+05
==============================================================================
Omnibus:                   163366.841   Durbin-Watson:                   1.436
Prob(Omnibus):                  0.000   Jarque-Bera (JB):       1190123756.356
Skew:                          16.472   Prob(JB):                         0.00
Kurtosis:                     597.005   Cond. No.                     3.37e+04
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 3.37e+04. This might indicate that there are
strong multicollinearity or other numerical problems.

<details open>
<summary style="background-color: #c6e2ff6c; padding: 10px; border-radius: 3px; box-shadow: 0 2px 4px rgba(0, 0, 0, 0.01); width: 95%; text-align: left; cursor: pointer; font-weight: bold;">
Expected output:</summary> 

<br>
<span style="font-size: 11px;">

```mkdn
                            OLS Regression Results                            
==============================================================================
Dep. Variable:                  price   R-squared:                       0.520
Model:                            OLS   Adj. R-squared:                  0.520
Method:                 Least Squares   F-statistic:                     5142.
Date:                Tue, 01 Apr 2025   Prob (F-statistic):               0.00
Time:                        14:47:19   Log-Likelihood:            -1.1959e+06
No. Observations:               80703   AIC:                         2.392e+06
Df Residuals:                   80685   BIC:                         2.392e+06
Df Model:                          17                                         
Covariance Type:            nonrobust                                         
===================================================================================
                      coef    std err          t      P>|t|      [0.025      0.975]
-----------------------------------------------------------------------------------
const           -3.902e+05   1.09e+04    -35.644      0.000   -4.12e+05   -3.69e+05
floorAreaSqM     9031.0844     55.507    162.702      0.000    8922.292    9139.877
bathrooms        1.859e+05   4392.856     42.321      0.000    1.77e+05    1.95e+05
region_E Outer  -1.876e+05   1.24e+04    -15.071      0.000   -2.12e+05   -1.63e+05
region_EC Inner  3.388e+05   2.22e+04     15.256      0.000    2.95e+05    3.82e+05
region_IG Outer  1.663e+04    6.6e+05      0.025      0.980   -1.28e+06    1.31e+06
region_N Inner  -1.871e+04    1.3e+04     -1.436      0.151   -4.42e+04    6821.538
region_N Outer   -2.05e+05   1.24e+04    -16.529      0.000   -2.29e+05   -1.81e+05
region_NW Inner   3.37e+05   1.68e+04     20.098      0.000    3.04e+05     3.7e+05
region_NW Outer -2.045e+05   1.52e+04    -13.444      0.000   -2.34e+05   -1.75e+05
region_Other     1.006e+06   1.63e+04     61.656      0.000    9.74e+05    1.04e+06
region_SE Inner -5.472e+04   1.23e+04     -4.462      0.000   -7.88e+04   -3.07e+04
region_SE Outer -2.057e+05   1.14e+04    -18.000      0.000   -2.28e+05   -1.83e+05
region_SW Inner  2.056e+05   1.26e+04     16.287      0.000    1.81e+05     2.3e+05
region_SW Outer -6.412e+04   1.29e+04     -4.961      0.000   -8.94e+04   -3.88e+04
region_W Inner   4.653e+05    1.5e+04     30.948      0.000    4.36e+05    4.95e+05
region_W Outer  -7.819e+04   1.52e+04     -5.143      0.000   -1.08e+05   -4.84e+04
region_WC Inner  4.786e+05    2.6e+04     18.418      0.000    4.28e+05     5.3e+05
==============================================================================
Omnibus:                   163366.841   Durbin-Watson:                   1.436
Prob(Omnibus):                  0.000   Jarque-Bera (JB):       1190123756.356
Skew:                          16.472   Prob(JB):                         0.00
Kurtosis:                     597.005   Cond. No.                     3.37e+04
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 3.37e+04. This might indicate that there are
strong multicollinearity or other numerical problems.
```
</span>
</details>

<details>
<summary style="background-color: #FDBFC7; padding: 10px; border-radius: 3px; box-shadow: 0 2px 4px rgba(0, 0, 0, 0.1); width: 95%; text-align: left; cursor: pointer; font-weight: bold;">
Click here to see the solution</summary> 

<ul style="background-color: #FFF8F8; padding: 10px; border-radius: 3px; margin-top: 5px; width: 95%; box-shadow: inset 0 2px 4px rgba(0, 0, 0, 0.1);">
   
Your solution should look something like this:

```python
# use "floorAreaSqM", "bathrooms" and "region" as predictors
predictors = ["floorAreaSqM", "bathrooms", "region"]

# get the dummy variables for the region column
features_with_dummies = pd.get_dummies(df[predictors], drop_first=True, dtype=int)

# add the constant term
X = sm.add_constant(features_with_dummies)

# get the target variable
Y = df["price"]

# create the model
model = sm.OLS(Y, X)

# fit the model
results = model.fit()

# print the model summary
print(results.summary())
```
</details>

As you can see, the R-squared value improved further to 0.520. Try some other variables to see if you can get the R-squared even higher!

Congratulations for making it until the end of this lab. You will keep working with the house prices in the last lesson. Hope you enjoyed it!